#include "stm32f10x.h"
#include "../../mcu_drivers/inc/drv_uart.h"
#include "../../mcu_drivers/inc/drv_timer.h"
#include "../../application/inc/protocol_handler.h"
#include "../../platform/inc/comm_hal.h"
