#include "stm32f10x.h"
#include "../../application/inc/protocol_handler.h"
#include "../../platform/inc/comm_hal.h"
#include "../../platform/inc/soft_timer.h"
#include "../../platform/inc/actuator_hal.h"
